version: "3.9"

services:
  people:
    container_name: people
    build: .
    working_dir: /src
    command: uvicorn appbinge.server:app --host 0.0.0.0 --reload
    environment:
      DEBUG: 1
    volumes:
      - ./src:/src  # Mounts the entire `src` directory correctly
    ports:
      - 8000:8000
    restart: on-failure